# Text Summarization Pagerank

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import string
import textwrap
# from wordcloud import WordCloud

from sklearn.feature_extraction.text import TfidfVectorizer
from nltk import sent_tokenize, word_tokenize
from sklearn.metrics.pairwise import cosine_similarity

## Data Loading

In [5]:
dataset_path = "bbc_text_cls.csv"
news_df = pd.read_csv(dataset_path, delimiter = ',')
sample_news = news_df[news_df.labels == "business"]['text'].sample(random_state = 42)

## Data Preprocessing

Remove Any Unnecessary Unicode Characters

In [6]:
stripped_sample_news = sample_news.replace('\n', "")\
                               .replace('\t', "")\
                               .replace('=', "")
                             
stripped_sample_news

480    Christmas sales worst since 1981\n\nUK retail ...
Name: text, dtype: object

Sentence Tokenizer

In [7]:
sentence_tokenized = sent_tokenize(sample_news.iloc[0])
sentence_tokenized

['Christmas sales worst since 1981\n\nUK retail sales fell in December, failing to meet expectations and making it by some counts the worst Christmas since 1981.',
 'Retail sales dropped by 1% on the month in December, after a 0.6% rise in November, the Office for National Statistics (ONS) said.',
 'The ONS revised the annual 2004 rate of growth down from the 5.9% estimated in November to 3.2%.',
 'A number of retailers have already reported poor figures for December.',
 'Clothing retailers and non-specialist stores were the worst hit with only internet retailers showing any significant growth, according to the ONS.',
 'The last time retailers endured a tougher Christmas was 23 years previously, when sales plunged 1.7%.',
 'The ONS echoed an earlier caution from Bank of England governor Mervyn King not to read too much into the poor December figures.',
 'Some analysts put a positive gloss on the figures, pointing out that the non-seasonally-adjusted figures showed a performance compara

## Data Modelling

### Compute TF-IDF

In [8]:
# def perform_tokenizer(sentence):
#     return sent_tokenize(sentence)

tf_idf_vectorizer = TfidfVectorizer(norm = 'l1')
tf_idf_matrix = tf_idf_vectorizer.fit_transform(sentence_tokenized)
tf_idf_matrix

<17x199 sparse matrix of type '<class 'numpy.float64'>'
	with 319 stored elements in Compressed Sparse Row format>

### Cosine Similarity

This gives us M * M matrix.

In [9]:
cosine_similarity_matrix = cosine_similarity(
    tf_idf_matrix
)
cosine_similarity_matrix.shape

(17, 17)

In [10]:
pd.DataFrame(
    cosine_similarity_matrix
)

0         1         2         3         4         5         6   \
0   1.000000  0.194654  0.078035  0.034468  0.106553  0.124564  0.053690   
1   0.194654  1.000000  0.240532  0.100899  0.068917  0.058394  0.099728   
2   0.078035  0.240532  1.000000  0.034798  0.185687  0.039309  0.201025   
3   0.034468  0.100899  0.034798  1.000000  0.073740  0.046836  0.173604   
4   0.106553  0.068917  0.185687  0.073740  1.000000  0.077995  0.088796   
5   0.124564  0.058394  0.039309  0.046836  0.077995  1.000000  0.021637   
6   0.053690  0.099728  0.201025  0.173604  0.088796  0.021637  1.000000   
7   0.037925  0.068686  0.061682  0.073493  0.116128  0.020982  0.079867   
8   0.087921  0.182963  0.172610  0.041766  0.084500  0.106910  0.075787   
9   0.043813  0.080670  0.018840  0.180949  0.074554  0.025358  0.070096   
10  0.050636  0.047505  0.172072  0.086262  0.103756  0.065901  0.119405   
11  0.024412  0.056024  0.057154  0.030669  0.039509  0.054528  0.037846   
12  0.192669  0.096984  0.114068  0.065425  0.094375  0.190303  0.021965   
13  0.057304  0.061119  0.000000  0.112473  0.110076  0.100456  0.000000   
14  0.042087  0.107054  0.058100  0.171821  0.084111  0.010393  0.146908   
15  0.091390  0.081372  0.057687  0.073067  0.013052  0.096114  0.261500   
16  0.050011  0.038076  0.118324  0.029816  0.079990  0.022454  0.161015   

          7         8         9         10        11        12        13  \
0   0.037925  0.087921  0.043813  0.050636  0.024412  0.192669  0.057304   
1   0.068686  0.182963  0.080670  0.047505  0.056024  0.096984  0.061119   
2   0.061682  0.172610  0.018840  0.172072  0.057154  0.114068  0.000000   
3   0.073493  0.041766  0.180949  0.086262  0.030669  0.065425  0.112473   
4   0.116128  0.084500  0.074554  0.103756  0.039509  0.094375  0.110076   
5   0.020982  0.106910  0.025358  0.065901  0.054528  0.190303  0.100456   
6   0.079867  0.075787  0.070096  0.119405  0.037846  0.021965  0.000000   
7   1.000000  0.158891  0.062966  0.084862  0.046667  0.054856  0.056557   
8   0.158891  1.000000  0.000000  0.104252  0.059426  0.069854  0.074659   
9   0.062966  0.000000  1.000000  0.046704  0.080105  0.171232  0.077569   
10  0.084862  0.104252  0.046704  1.000000  0.049002  0.028440  0.029719   
11  0.046667  0.059426  0.080105  0.049002  1.000000  0.119793  0.100299   
12  0.054856  0.069854  0.171232  0.028440  0.119793  1.000000  0.058529   
13  0.056557  0.074659  0.077569  0.029719  0.100299  0.058529  1.000000   
14  0.090770  0.023871  0.039420  0.021775  0.042383  0.039089  0.030344   
15  0.048192  0.042659  0.146167  0.052985  0.063169  0.062499  0.044690   
16  0.035234  0.051570  0.053077  0.071161  0.116082  0.049533  0.020661   

          14        15        16  
0   0.042087  0.091390  0.050011  
1   0.107054  0.081372  0.038076  
2   0.058100  0.057687  0.118324  
3   0.171821  0.073067  0.029816  
4   0.084111  0.013052  0.079990  
5   0.010393  0.096114  0.022454  
6   0.146908  0.261500  0.161015  
7   0.090770  0.048192  0.035234  
8   0.023871  0.042659  0.051570  
9   0.039420  0.146167  0.053077  
10  0.021775  0.052985  0.071161  
11  0.042383  0.063169  0.116082  
12  0.039089  0.062499  0.049533  
13  0.030344  0.044690  0.020661  
14  1.000000  0.101206  0.041055  
15  0.101206  1.000000  0.104910  
16  0.041055  0.104910  1.000000

Divide each row, so each row sums up to 1.

In [11]:
sum_all_rows = cosine_similarity_matrix.sum(axis = 1, dtype = 'float64')
print(sum_all_rows)

[2.27013241 2.58357841 2.60992313 2.33008611 2.40173849 2.06213552
 2.61287022 2.09775769 2.33763944 2.17152224 2.13443788 1.97706875
 2.4296146  1.93445416 2.05038987 2.34066007 2.04296773]


In [12]:
normalized_cosine_similarity_matrix = cosine_similarity_matrix / sum_all_rows.reshape(-1, 1)
print(normalized_cosine_similarity_matrix.shape)
print(normalized_cosine_similarity_matrix.sum(axis = 1))
print(normalized_cosine_similarity_matrix[0].sum())

(17, 17)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
0.9999999999999999


Find Uniform Matrix

It contains 1 / M. M represents number of sentences.

In [13]:
number_of_sentences = normalized_cosine_similarity_matrix.shape[0]
uniform_matrix = np.full(fill_value = 1 / number_of_sentences, shape = (number_of_sentences, number_of_sentences))

uniform_matrix.shape

(17, 17)

Find A, by this formula:

${A = αU + (1 - α) * G}$

The formula is used for perform smoothing.

Where:
* G = Similarity Matrix
* U = Uniform matrix

In [14]:
def get_text_rank_matrix(similarity_matrix, 
                         uniform_matrix,
                         alpha = 0.15):
    return alpha * uniform_matrix + (1 - alpha) * similarity_matrix

text_rank_matrix = get_text_rank_matrix(normalized_cosine_similarity_matrix, uniform_matrix)

pd.DataFrame(text_rank_matrix)

0         1         2         3         4         5         6   \
0   0.383251  0.081707  0.038042  0.021729  0.048720  0.055464  0.028927   
1   0.072865  0.337825  0.087959  0.042019  0.031497  0.028035  0.041634   
2   0.034238  0.087160  0.334504  0.020156  0.069298  0.021626  0.074293   
3   0.021397  0.045631  0.021518  0.373617  0.035723  0.025909  0.072153   
4   0.046534  0.033214  0.074540  0.034921  0.362734  0.036427  0.040249   
5   0.060168  0.032893  0.025026  0.028129  0.040973  0.421018  0.017742   
6   0.026290  0.041266  0.074219  0.065299  0.037710  0.015862  0.334136   
7   0.024191  0.036655  0.033817  0.038603  0.055878  0.017325  0.041185   
8   0.040793  0.075352  0.071587  0.024010  0.039549  0.047698  0.036381   
9   0.025973  0.040400  0.016198  0.079652  0.038006  0.018749  0.036261   
10  0.028988  0.027742  0.077348  0.043176  0.050142  0.035067  0.056374   
11  0.019319  0.032910  0.033396  0.022009  0.025810  0.032267  0.025095   
12  0.076229  0.042754  0.048730  0.031712  0.041841  0.075401  0.016508   
13  0.034003  0.035679  0.008824  0.058244  0.057191  0.052964  0.008824   
14  0.026271  0.053204  0.032909  0.080053  0.043692  0.013132  0.069725   
15  0.042011  0.038373  0.029772  0.035358  0.013563  0.043727  0.103786   
16  0.029631  0.024665  0.058054  0.021229  0.042104  0.018166  0.075816   

          7         8         9         10        11        12        13  \
0   0.023024  0.041743  0.025228  0.027783  0.017964  0.080964  0.030280   
1   0.031421  0.069019  0.035364  0.024453  0.027255  0.040732  0.028932   
2   0.028912  0.065039  0.014959  0.064864  0.027438  0.045973  0.008824   
3   0.035633  0.024060  0.074833  0.040291  0.020011  0.032690  0.049853   
4   0.049922  0.038729  0.035209  0.045544  0.022806  0.042224  0.047781   
5   0.017472  0.052891  0.019276  0.035988  0.031300  0.087265  0.050231   
6   0.034805  0.033478  0.031627  0.047668  0.021135  0.015969  0.008824   
7   0.414018  0.073205  0.034337  0.043209  0.027733  0.031051  0.031740   
8   0.066599  0.372438  0.008824  0.046731  0.030432  0.034224  0.035970   
9   0.033470  0.008824  0.400254  0.027105  0.040179  0.075849  0.039186   
10  0.042618  0.050340  0.027423  0.407055  0.028338  0.020149  0.020659   
11  0.028887  0.034373  0.043263  0.029891  0.438753  0.060326  0.051945   
12  0.028015  0.033262  0.068729  0.018773  0.050733  0.358673  0.029300   
13  0.033675  0.041629  0.042907  0.021882  0.052895  0.034541  0.448224   
14  0.046453  0.018719  0.025165  0.017850  0.026394  0.025028  0.021403   
15  0.026324  0.024315  0.061903  0.028065  0.031763  0.031520  0.025052   
16  0.023483  0.030280  0.030907  0.038431  0.057121  0.029432  0.017420   

          14        15        16  
0   0.024582  0.043043  0.027549  
1   0.044045  0.035595  0.021350  
2   0.027746  0.027611  0.047359  
3   0.071503  0.035478  0.019700  
4   0.038591  0.013443  0.037133  
5   0.013108  0.048441  0.018079  
6   0.056614  0.093893  0.061204  
7   0.045603  0.028351  0.023100  
8   0.017503  0.024335  0.027575  
9   0.024254  0.066038  0.029600  
10  0.017495  0.029924  0.037162  
11  0.027045  0.035982  0.058730  
12  0.022499  0.030689  0.026152  
13  0.022157  0.028460  0.017902  
14  0.423379  0.050779  0.025843  
15  0.045576  0.371969  0.046921  
16  0.025905  0.052472  0.424885

**Check The Matrix using Perron Frobenius Theorem**

Perron Frobenius Theorem satifies these conditions:
* All values in markov matrix is positive
* Each rows in markov matrix sums to 1, and all values are non negative

In [15]:
print((text_rank_matrix >= 0).sum())
print(text_rank_matrix.sum(axis = 1))

289
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Get the eigenfactors

In [16]:
np.set_printoptions(suppress = True)

# Find the limiting/ Stationery Distribution
# As mentioned by convention, we think of eigenvalue equation in term of column vectors instead of row vectors.
# V is a column vector and P is a row vector

# If np.eig(A) = Av = λv 
# If np.eig(A.T) = pA = λp or A^T p^T = λp^T

# State distribution becomes column vector and our matrix is transposed.
eigenvalues, normalized_eigenvectors = np.linalg.eig(text_rank_matrix.T)
print(eigenvalues)
print(normalized_eigenvectors[:, 0])

[1.         0.4918176  0.20696347 0.22797545 0.46795011 0.44642103
 0.43191473 0.26524854 0.27269963 0.28872484 0.31396721 0.32402682
 0.3541479  0.36500825 0.37066593 0.3925564  0.38664392]
[-0.24200551 -0.26819835 -0.26980595 -0.24821263 -0.25392628 -0.22607829
 -0.27095827 -0.22868495 -0.24795614 -0.23490663 -0.23100659 -0.22023878
 -0.25680024 -0.2170586  -0.22420059 -0.24853495 -0.22397371]


In [17]:
# Check whether our eigenvector has the same value when multiplied by the matrix.
# If it does, it's the proper vector.
normalized_eigenvectors[:, 0].dot(text_rank_matrix)

array([-0.24200551, -0.26819835, -0.26980595, -0.24821263, -0.25392628,
       -0.22607829, -0.27095827, -0.22868495, -0.24795614, -0.23490663,
       -0.23100659, -0.22023878, -0.25680024, -0.2170586 , -0.22420059,
       -0.24853495, -0.22397371])

Get the index with eigenvalue 1.

In [18]:
def get_index_from_specified_value(my_array, find_value):
    equivalent_indexes = []
    for index, value in enumerate(my_array):
        print(value)
        if np.isclose(value, find_value):
            equivalent_indexes.append(index)

    return equivalent_indexes

valid_indexes = get_index_from_specified_value(eigenvalues, 1.)
valid_indexes

1.0000000000000007
0.49181760001405883
0.20696347318976407
0.22797544972808556
0.46795011069862275
0.44642103400426
0.4319147318754193
0.2652485356459734
0.27269963063794933
0.2887248443033925
0.31396721364928176
0.32402682301694413
0.35414790485210823
0.365008254982586
0.37066593281973365
0.39255639703649414
0.38664391526821784


[0]

In [19]:
scores = normalized_eigenvectors[:, valid_indexes]
print(scores)

[[-0.24200551]
 [-0.26819835]
 [-0.26980595]
 [-0.24821263]
 [-0.25392628]
 [-0.22607829]
 [-0.27095827]
 [-0.22868495]
 [-0.24795614]
 [-0.23490663]
 [-0.23100659]
 [-0.22023878]
 [-0.25680024]
 [-0.2170586 ]
 [-0.22420059]
 [-0.24853495]
 [-0.22397371]]


Check if still holds probability distribution.  Eigenvectors are not unique.

In [20]:
scores = normalized_eigenvectors[:, 0] / normalized_eigenvectors[:, 0].sum()
scores

array([0.05884566, 0.06521467, 0.06560557, 0.06035497, 0.06174429,
       0.05497282, 0.06588577, 0.05560665, 0.06029261, 0.05711951,
       0.05617118, 0.0535529 , 0.06244312, 0.05277961, 0.05451624,
       0.06043335, 0.05446108])

### Optional

Direct method on finding limiting distribution. This is finding limiting distribution by brute force. We're going to the transitions until distribution converges.

In [21]:
limiting_dist = np.ones(len(text_rank_matrix)) / len(text_rank_matrix)
threshold = 1e-8 # To quit the llop
delta = float('inf') # Show how much distribution has changed from one step to next.

iters = 0
while delta > threshold:
    iters += 1

    # Compute the distribution for the next step. (markov transition)
    # By multiplying the distribution by X.
    p = limiting_dist.dot(text_rank_matrix)

    # Compute next delta. (compute change in limiting distribution)
    # This is the sum of absolute differences between new and old distributions.
    delta = np.abs(p - limiting_dist).sum()

    # Update limiting distribution.
    limiting_dist = p

    print(iters)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


See the result

In [22]:
limiting_dist

array([0.05884566, 0.06521467, 0.06560557, 0.06035497, 0.06174429,
       0.05497282, 0.06588577, 0.05560665, 0.06029261, 0.05711951,
       0.05617118, 0.0535529 , 0.06244312, 0.05277961, 0.05451624,
       0.06043335, 0.05446108])

Check if limiting_dist sums up to 1.

In [23]:
limiting_dist.sum()

0.9999999999999996

Compute sum of absolute differences before, and the answer we got by brute force.

In [24]:
np.abs(normalized_eigenvectors[:, 0] / normalized_eigenvectors[:, 0] - limiting_dist).sum()

16.0

## Result

Combine Sentences if the value inside the eigenvector is more than 0

In [25]:
def get_summarized_text(sentences, scores, threshold = 0.06):
    summarized_texts = []
    for sentence, score in zip(sentences, scores):
        if score > threshold:
            summarized_texts.append(sentence)

    return summarized_texts

get_summarized_text(sentence_tokenized, scores)

['Retail sales dropped by 1% on the month in December, after a 0.6% rise in November, the Office for National Statistics (ONS) said.',
 'The ONS revised the annual 2004 rate of growth down from the 5.9% estimated in November to 3.2%.',
 'A number of retailers have already reported poor figures for December.',
 'Clothing retailers and non-specialist stores were the worst hit with only internet retailers showing any significant growth, according to the ONS.',
 'The ONS echoed an earlier caution from Bank of England governor Mervyn King not to read too much into the poor December figures.',
 'The November-December jump last year was roughly comparable with recent averages, although some way below the serious booms seen in the 1990s.',
 'And a British Retail Consortium survey found that Christmas 2004 was the worst for 10 years.',
 '"The retail sales figures are very weak, but as Bank of England governor Mervyn King indicated last night, you don\'t really get an accurate impression of Chri

Compare the answer with actual news.

In [26]:
print(textwrap.fill(sample_news.iloc[0], replace_whitespace=False, fix_sentence_endings=True))

Christmas sales worst since 1981

UK retail sales fell in December,
failing to meet expectations and making it by some counts the worst
Christmas since 1981.

Retail sales dropped by 1% on the month in
December, after a 0.6% rise in November, the Office for National
Statistics (ONS) said.  The ONS revised the annual 2004 rate of growth
down from the 5.9% estimated in November to 3.2%. A number of
retailers have already reported poor figures for December.  Clothing
retailers and non-specialist stores were the worst hit with only
internet retailers showing any significant growth, according to the
ONS.

The last time retailers endured a tougher Christmas was 23 years
previously, when sales plunged 1.7%.

The ONS echoed an earlier
caution from Bank of England governor Mervyn King not to read too much
into the poor December figures.  Some analysts put a positive gloss on
the figures, pointing out that the non-seasonally-adjusted figures
showed a performance comparable with 2003. The Novembe

## Putting it all together.

In [49]:
class PageRank():
    def _get_page_rank_matrix(self, sentences_tokenized, alpha = 0.15):
        tf_idf_vectorizer = TfidfVectorizer(norm = 'l1')
        tf_idf_matrix = tf_idf_vectorizer.fit_transform(sentence_tokenized)

        cosine_similarity_matrix = cosine_similarity(
            tf_idf_matrix
        )

        sum_all_rows = cosine_similarity_matrix.sum(axis = 1, dtype = 'float64')
        normalized_cosine_similarity_matrix = cosine_similarity_matrix / sum_all_rows.reshape(-1, 1)
        number_of_sentences = normalized_cosine_similarity_matrix.shape[0]
        uniform_matrix = np.full(fill_value = 1 / number_of_sentences, shape = (number_of_sentences, number_of_sentences))
        text_rank_matrix = alpha * uniform_matrix + (1 - alpha) * normalized_cosine_similarity_matrix
        eigenvalues, normalized_eigenvectors = np.linalg.eig(text_rank_matrix.T)

        return text_rank_matrix

    def _get_scores(self, text_rank_matrix):
        eigenvalues, normalized_eigenvectors = np.linalg.eig(text_rank_matrix.T)
        valid_index = self._get_index_from_specified_value(eigenvalues, 1.)[0]
        scores = normalized_eigenvectors[:, valid_index]
        scores = normalized_eigenvectors[:, valid_index] / normalized_eigenvectors[:, valid_index].sum()
        return scores

    def _get_index_from_specified_value(self, my_array, find_value):
        equivalent_indexes = []
        for index, value in enumerate(my_array):
            if np.isclose(value, find_value):
                equivalent_indexes.append(index)

        return equivalent_indexes

    def _get_summarized_text(self, sentences, scores, threshold = 0.06):
        summarized_texts = []
        for sentence, score in zip(sentences, scores):
            if score > threshold:
                summarized_texts.append(sentence)

        return summarized_texts

    def summarize_text(self, sentences):
        sentence_tokenized = sent_tokenize(sentences)
        text_rank_matrix = self._get_page_rank_matrix(sentence_tokenized)
        scores = self._get_scores(text_rank_matrix)
        return self._get_summarized_text(sentence_tokenized, scores)
        
page_rank = PageRank()
# print(stripped_sample_news)
page_rank.summarize_text(stripped_sample_news.iloc[0])

['Retail sales dropped by 1% on the month in December, after a 0.6% rise in November, the Office for National Statistics (ONS) said.',
 'The ONS revised the annual 2004 rate of growth down from the 5.9% estimated in November to 3.2%.',
 'A number of retailers have already reported poor figures for December.',
 'Clothing retailers and non-specialist stores were the worst hit with only internet retailers showing any significant growth, according to the ONS.',
 'The ONS echoed an earlier caution from Bank of England governor Mervyn King not to read too much into the poor December figures.',
 'The November-December jump last year was roughly comparable with recent averages, although some way below the serious booms seen in the 1990s.',
 'And a British Retail Consortium survey found that Christmas 2004 was the worst for 10 years.',
 '"The retail sales figures are very weak, but as Bank of England governor Mervyn King indicated last night, you don\'t really get an accurate impression of Chri